use_directory_urls: false
site_name: Fungus
site_url: http://fungusgames.com
site_description: Documentation and user guide for the open source Fungus storytelling tool
site_favicon: images/favicon.ico
site_dir: ../snozbot.github.io
google_analytics: ['UA-70024522-1', 'auto']
pages:
- Fungus Docs:
    - Overview: index.md
    - What is Fungus?: about/index.md
    - Installation: download/index.md
    - Getting Started: getting_started/index.md
    - Flowcharts: flowcharts/index.md
    - Blocks: blocks/index.md
    - Telling a Story: telling_a_story/index.md
    - Playing Audio: playing_audio/index.md
    - Community Articles: articles/index.md
    - Glossary: glossary/index.md
    - FAQ: faq/index.md
    - Reference:
        - Animation Commands: commands/animation_commands.md
        - Audio Commands: commands/audio_commands.md
        - Camera Commands: commands/camera_commands.md
        - Flow Commands: commands/flow_commands.md
        - iTween Commands: commands/itween_commands.md
        - Narrative Commands: commands/narrative_commands.md
        - Scripting Commands: commands/scripting_commands.md
        - Sprite Commands: commands/sprite_commands.md
        - Variable Commands: commands/variable_commands.md
        - Events (Core) Commands: commands/event_handlers/core_events.md
        - Events (Input) Commands: commands/event_handlers/input_events.md
        - Events (Sprite) Commands: commands/event_handlers/sprite_events.md
        - Narrative Parser Tokens: advanced/narrative_parser_tokens.md
- FungusLua Docs (Beta): 
    - Overview: fungus_lua/index.md
    - Create Menu: fungus_lua/create_menu.md
    - Lua Environment: fungus_lua/lua_environment.md
    - Lua Bindings: fungus_lua/lua_bindings.md
    - Lua Script: fungus_lua/lua_script.md
    - Lua Utils: fungus_lua/lua_utils.md
    - Fungus Module: fungus_lua/fungus_module.md
    - Controlling Fungus: fungus_lua/controlling_fungus.md
    - ExecuteLua command: fungus_lua/execute_lua.md
    - Preferences: fungus_lua/preferences.md
    - Lua Store: fungus_lua/lua_store.md
    - String Table: fungus_lua/string_table.md
    - Unity Test Tools: fungus_lua/unity_test_tools.md
- Tutorial Videos: tutorial_videos/index.md
- Training Course: training_course/index.md

#    - Code of Conduct: conduct/index.md
#- Forum: forum/index.md

theme_dir: 'custom_theme'
theme: spacelab


